# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_IMAGE: sreegrandhe/orbitdbpinner
  
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    name: Upload Docker Image to Docker Hub
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: sreegrandhe
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:latest
    -
      name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      env:
        CONTAINER_NAME: "pinning_server"
      with:
        host: pinning.three0dev.com
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        envs: DOCKER_IMAGE, CONTAINER_NAME
        script: |
          docker kill $CONTAINER_NAME
          docker pull $DOCKER_IMAGE:latest
          docker run -d --name $CONTAINER_NAME -p 80:8000 $DOCKER_IMAGE